[controller]
pi4 ansible_connection=local mpi_host=localhost mpi_slots=4

[cluster_nodes]
p1 ansible_host=p1 mpi_slots=4
p2 ansible_host=p2 mpi_slots=4
p3 ansible_host=p3 mpi_slots=1
p4 ansible_host=p4 mpi_slots=1

[zero2w]
p1
p2

[zerow]
p3
p4

[cluster_all:children]
controller
cluster_nodes
